Repository FuelLabs/fuel-specs, pull requests merged in 2022-04, with the labels that each got.

#300 fix: use `uint32` type for all `maturity` fields
  specs/protocol/tx_format.md
Labels: bug, comp:VAL

#307 docs: give the meaning of `MEM[x, y]`
  specs/vm/opcodes.md
Labels: documentation

#304 update: tuples have components
  specs/protocol/abi.md
Labels: ABI
