Repository FuelLabs/fuel-specs, pull requests merged in 2022-11, with the labels that each got.

#425 Move specs into an `mdbook`. Add CI for deploying.
  .github/workflows/gh-pages.yml
  .github/workflows/mdbook.yml
  .gitignore
  README.md
  book.toml
  specs/network/index.md
  specs/protocol/identifiers.md
  specs/protocol/tx_format.md
  src/SUMMARY.md
  src/fuel-specs.md
  src/network/index.md
  src/network/poa.md
  src/protocol/abi.md
  src/protocol/block_header.md
  src/protocol/cryptographic_primitives.md
  src/protocol/id/contract.md
  src/protocol/id/index.md
  src/protocol/id/transaction.md
  src/protocol/id/utxo.md
  src/protocol/index.md
  src/protocol/storage_initialization.md
  src/protocol/tx_format/constants.md
  src/protocol/tx_format/index.md
  src/protocol/tx_format/input.md
  src/protocol/tx_format/output.md
  src/protocol/tx_format/transaction.md
  src/protocol/tx_format/tx_pointer.md
  src/protocol/tx_format/witness.md
  src/protocol/tx_validity.md
  src/tests/index.md
  src/tests/sparse_merkle_tree_tests.md
  src/vm/index.md
  src/vm/instruction_set.md
Labels: documentation, enhancement

#419 Configuration-time constants in the ABI
  src/protocol/abi.md
Labels: ABI

#433 Split `abi.md` into multiple files
  book.toml
  src/SUMMARY.md
  src/fuel-specs.md
  src/protocol/abi.md
  src/protocol/abi/fn_selector_encoding.md
  src/protocol/abi/index.md
  src/protocol/abi/json_abi_format.md
  src/protocol/abi/receipts.md
  src/protocol/index.md
Labels: documentation

#434 Fix redirect
  book.toml
Labels: bug

#432 Minor enhancement to storage instructions + various nits
  src/protocol/block_header.md
  src/protocol/storage_initialization.md
  src/protocol/tx_format/input.md
  src/protocol/tx_format/output.md
  src/protocol/tx_format/transaction.md
  src/vm/index.md
  src/vm/instruction_set.md
Labels: comp:FVM
