Repository FuelLabs/fuel-specs, pull requests merged in 2022-06, with the labels that each got.

#327 Fix `balanceOfStart` usage.
  specs/vm/opcodes.md
Labels: bug, documentation, comp:FVM

#332 Remove static contracts from tx.
  specs/protocol/tx_format.md
  specs/protocol/tx_validity.md
Labels: comp:VAL

#335 Specify exp result value on overflow.
  specs/vm/opcodes.md
Labels: comp:FVM

#330 Remove SLDC instruction.
  specs/vm/opcodes.md
Labels: comp:FVM

#337 Second half of renaming opcodes to instructions.
  specs/vm/instruction_set.md
  specs/vm/main.md
Labels: documentation

#341 Expanding the section on enum ABI encoding with more exmaples
  specs/protocol/abi.md
Labels: ABI

#345 Rename native -> base
  specs/protocol/tx_validity.md
Labels: documentation

#344 Remove reference to Ethereum.
  specs/protocol/tx_validity.md
Labels: documentation

#343 Add gas price factor.
  specs/protocol/tx_format.md
  specs/protocol/tx_validity.md
Labels: comp:FVM, comp:VAL

#350 Clarify how the function selector is computed using a table and a more complex example
  specs/protocol/abi.md
Labels: ABI

#349 renamed predicate hash to root
  specs/protocol/tx_format.md
Labels: comp:VAL

#352 Specify JSON format for storage initializers
  README.md
  specs/protocol/storage_initialization.md
Labels: ABI

#354 Make readme intro blazingly fast
  README.md
Labels: documentation, admin

#318 New messaging specification (replacing old deposit/withdrawal spec)
  specs/protocol/abi.md
  specs/protocol/identifiers.md
  specs/protocol/tx_format.md
  specs/protocol/tx_validity.md
  specs/vm/instruction_set.md
  specs/vm/main.md
Labels: enhancement, comp:FVM, comp:VAL

#361 Typo in Output Message ID
  specs/protocol/identifiers.md
Labels: documentation, good first issue

#353 Add instructions to get tx fields
  specs/vm/instruction_set.md
Labels: comp:FVM

#372 Check script and predicate / data lengths.
  specs/protocol/tx_format.md
Labels: comp:VAL

#377 Change the bullet points to headings in `/specs/protocol/abi.md` so that they can be clicked and used as direct links
  specs/protocol/abi.md
Labels: documentation, good first issue
