Repository FuelLabs/fuel-specs, pull requests merged in 2022-03, with the labels that each got.

#283 Update Array ABI spec
  specs/protocol/abi.md
Labels: ABI

#288 Always append a result receipt on revert.
  specs/vm/opcodes.md
Labels: bug, comp:FVM

#290 Clarify registers used in CALL.
  specs/vm/opcodes.md
Labels: documentation, comp:FVM

#291 Maximum number of initial storage slots.
  specs/protocol/tx_format.md
Labels: comp:VAL

#292 Fix reg ID typo in CALL
  specs/vm/opcodes.md
Labels: bug, comp:FVM

#296 Add MOVI instruction.
  specs/vm/opcodes.md
Labels: enhancement, comp:FVM

#299 Fix typos
  specs/vm/opcodes.md
Labels: bug, documentation
