Repository FuelLabs/fuel-specs, pull requests merged in 2022-01, with the labels that each got.

#258 Require at least one coin input.
  specs/protocol/tx_format.md
Labels: bug, comp:VAL

#263 add byte pricing independent of gas price
  specs/chains/ethereum/compressed_tx_format.md
  specs/protocol/tx_format.md
  specs/protocol/tx_validity.md
Labels: enhancement, comp:VAL

#266 Add rule to verify predicate hash
  specs/protocol/identifiers.md
  specs/protocol/tx_format.md
Labels: bug, comp:VAL

#269 Remove bal init for scripts.
  specs/vm/main.md
Labels: bug, comp:FVM

#267 Transclude signature spec.
  specs/protocol/cryptographic_primitives.md
  specs/protocol/tx_validity.md
  specs/vm/opcodes.md
Labels: documentation, comp:VAL

#268 Clarify that non-witness data is not part of tx ID.
  specs/protocol/identifiers.md
Labels: bug, comp:VAL
