Repository FuelLabs/fuel-specs, pull requests merged in 2022-08, with the labels that each got.

#393 Remove separate transaction access instructions
  specs/vm/instruction_set.md
Labels: comp:FVM

#398 Fix `GTF_INPUT_MESSAGE_NONCE` to use word instead of bytes.
  specs/vm/instruction_set.md
Labels: bug, comp:FVM

#396 Add timestamp instruction.
  specs/vm/instruction_set.md
Labels: enhancement, comp:FVM

#397 Create markdown-lint.yml
  .github/workflows/markdown-lint.yml
  .markdownlint.yaml
  README.md
  specs/protocol/abi.md
  specs/protocol/cryptographic_primitives.md
  specs/protocol/tx_format.md
  specs/tests/sparse_merkle_tree_tests.md
  specs/vm/instruction_set.md
Labels: admin
