Repository FuelLabs/fuel-specs, pull requests merged in 2023-03, with the labels that each got.

#464 Make `$hp` point to immediately after usable memory.
  src/vm/index.md
  src/vm/instruction_set.md
Labels: comp:FVM

#465 Add nested call limit
  src/protocol/tx_format/constants.md
  src/vm/instruction_set.md
Labels: documentation, comp:FVM

#466 Make $hp point to the first available byte, instead of the one before it
  src/vm/index.md
  src/vm/instruction_set.md
Labels: documentation, comp:FVM

#468 Document the panic conditions of logd
  src/vm/instruction_set.md
Labels: documentation, comp:FVM

#473 Remove nested call limit
  src/protocol/tx_format/constants.md
  src/vm/instruction_set.md
Labels: comp:FVM

#470 Add relative jump opcodes
  src/vm/instruction_set.md
Labels: enhancement, comp:FVM
