Repository FuelLabs/fuel-specs, pull requests merged in 2023-07, with the labels that each got.

#501 Clarify the gas forwarded field in call receipt
  src/fuel-vm/instruction-set.md
Labels: documentation, comp:FVM

#502 Fix typo in instruction-set.md
  src/fuel-vm/instruction-set.md
Labels: documentation

#499 Add scattered push/pop operations
  src/fuel-vm/instruction-set.md
Labels: comp:FVM

#504 docs: Add Merkle tree specs to cryptographic primitives
  src/protocol/cryptographic-primitives.md
Labels: documentation

#506 Do not restore $hp when returning from a context
  src/fuel-vm/instruction-set.md
Labels: enhancement, comp:FVM
