Repository FuelLabs/fuel-specs, pull requests merged in 2024-07, with the labels that each got.

#588 Clean up overflow conditions
  src/fuel-vm/instruction-set.md
Labels: comp:FVM

#596 Updates ABI spec with hash based ids, versions and program type.
  src/SUMMARY.md
  src/abi/hash-based-ids.md
  src/abi/index.md
  src/abi/json-abi-format.md
  src/fuel-vm/index.md
Labels: ABI

#599 Adds concrete types distinction to JSON ABI.
  src/abi/json-abi-format.md
Labels: ABI

#601 Fix `cfei -> cfe` typo in `instruction-set.md`
  src/fuel-vm/instruction-set.md
Labels: documentation, comp:FVM

#592 Blob tx and instructions
  src/SUMMARY.md
  src/fuel-vm/instruction-set.md
  src/identifiers/blob-id.md
  src/identifiers/index.md
  src/tx-format/index.md
  src/tx-format/transaction.md
Labels: enhancement, comp:FVM
